import { Match, Mood } from './types';

export const GAME_DIFFICULTIES = {
    FREE: 'free',
    EASY: 'easy',
    even: 'even',
    hard: 'hard',
    IMPOSSIBLE: 'impossible',
    SELF_IMPACT: 'self-impact'
} as const;

export const GAME_DIFFICULTY_LABELS: Record<Match['gameDifficulty'], string> = {
    free: 'Free game',
    easy: 'Easy game',
    even: 'Even game',
    hard: 'Hard game',
    impossible: 'Impossible game',
    'self-impact': 'Self impact'
} as const;

export const ROLES = [1, 2, 3, 4, 5] as const;

export const ROLE_LABELS: Record<Match['role'], string> = {
    1: 'Carry',
    2: 'Mid',
    3: 'Offlane',
    4: 'Soft Support',
    5: 'Hard Support'
} as const;

export const MOODS: Record<Mood, { label: string; color: string }> = {
    great: { label: 'Great', color: '#4CAF50' },
    good: { label: 'Good', color: '#8BC34A' },
    neutral: { label: 'Neutral', color: '#FFC107' },
    bad: { label: 'Bad', color: '#FF9800' },
    terrible: { label: 'Terrible', color: '#F44336' }
} as const;

export const GAME_RESULT = {
    WIN: 'win',
    LOSS: 'loss'
} as const;

export const GAME_RESULT_LABELS: Record<Match['result'], string> = {
    win: 'Victory',
    loss: 'Defeat'
} as const;

export const HEROES = [
    "Abaddon",
    "Alchemist",
    "Ancient Apparition",
    "Anti-Mage",
    "Arc Warden",
    "Axe",
    "Bane",
    "Batrider",
    "Beastmaster",
    "Bloodseeker",
    "Bounty Hunter",
    "Brewmaster",
    "Bristleback",
    "Broodmother",
    "Centaur Warrunner",
    "Chaos Knight",
    "Chen",
    "Clinkz",
    "Clockwerk",
    "Crystal Maiden",
    "Dark Seer",
    "Dark Willow",
    "Dawnbreaker",
    "Dazzle",
    "Death Prophet",
    "Disruptor",
    "Doom",
    "Dragon Knight",
    "Drow Ranger",
    "Earth Spirit",
    "Earthshaker",
    "Elder Titan",
    "Ember Spirit",
    "Enchantress",
    "Enigma",
    "Faceless Void",
    "Grimstroke",
    "Gyrocopter",
    "Hoodwink",
    "Huskar",
    "Invoker",
    "Io",
    "Jakiro",
    "Juggernaut",
    "Keeper of the Light",
    "Kez",
    "Kunkka",
    "Legion Commander",
    "Leshrac",
    "Lich",
    "Lifestealer",
    "Lina",
    "Lion",
    "Lone Druid",
    "Luna",
    "Lycan",
    "Magnus",
    "Marci",
    "Mars",
    "Medusa",
    "Meepo",
    "Mirana",
    "Monkey King",
    "Morphling",
    "Muerta",
    "Naga Siren",
    "Nature's Prophet",
    "Necrophos",
    "Night Stalker",
    "Nyx Assassin",
    "Ogre Magi",
    "Omniknight",
    "Oracle",
    "Outworld Destroyer",
    "Pangolier",
    "Phantom Assassin",
    "Phantom Lancer",
    "Phoenix",
    "Primal Beast",
    "Puck",
    "Pudge",
    "Pugna",
    "Queen of Pain",
    "Razor",
    "Riki",
    "Ringmaster",
    "Rubick",
    "Sand King",
    "Shadow Demon",
    "Shadow Fiend",
    "Shadow Shaman",
    "Silencer",
    "Skywrath Mage",
    "Slardar",
    "Slark",
    "Snapfire",
    "Sniper",
    "Spectre",
    "Spirit Breaker",
    "Storm Spirit",
    "Sven",
    "Techies",
    "Templar Assassin",
    "Terrorblade",
    "Tidehunter",
    "Timbersaw",
    "Tinker",
    "Tiny",
    "Treant Protector",
    "Troll Warlord",
    "Tusk",
    "Underlord",
    "Undying",
    "Ursa",
    "Vengeful Spirit",
    "Venomancer",
    "Viper",
    "Visage",
    "Void Spirit",
    "Warlock",
    "Weaver",
    "Windranger",
    "Winter Wyvern",
    "Witch Doctor",
    "Wraith King",
    "Zeus"
  ] as const;